import { Schema } from "mongoose";

const User = new Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    pw:{
        type:String,
        required:true
    },
    qnt:{
        type:String,
        required:false
    },
    movies:{
        type:Array,
        required:false
    },
    categories:{
        type:Array,
        required:false
    }
})
const movieSchema = new Schema({
    title:{
        type:String,
        required:true
    },
    phase:{
        type:String,
        required:false
    },
    category_name:{
        type:Array,
        required:false
    },
    cast:{
        type:Array,
        required:false
    },
    release_year:{
        type:Number,
        required:false
    },
    running_time:{
        type:Number,
        required:false
    },
    rating_name:{
        type:String,
        required:false
    },
    disc_format_name:{
        type:String,
        required:false
    },
    number_discs:{
        type:Number,
        required:false
    },
    viewing_format_name:{
        type:String,
        required:false
    },
    aspect_ratio_name:{
        type:String,
        required:false
    },
    status:{
        type:Number,
        required:false
    },
    release_date:{
        type:String,
        required:false
    },
    budget:{
        type:String,
        required:false
    },
    gross:{
        type:String,
        required:false
    },
    time_stamp:{
        type:String,
        required:false
    }
})
const actors = new Schema({
    name:{
        type:String,
        required:false
    },
    rating:{
        type:Number,
        required:false
    },
    alternative_name:{
        type:String,
        required:false
    }
});
const categorie = new Schema({
    categorie:String
});
const feedMovie = new Schema({
    Title:{
        required:false,
        type:String
    },
    Year:{
        required:false,
        type:String
    },
    Rated:{
        required:false,
        type:String
    },
    Released:{
        required:false,
        type:String
    },
    Runtime:{
        required:false,
        type:String
    },
    Genre:{
        required:false,
        type:String
    },
    Director:{
        required:false,
        type:String
    },
    Writer:{
        required:false,
        type:String
    },
    Actors:{
        required:false,
        type:String
    },
    Plot:{
        required:false,
        type:String
    },
    Language:{
        required:false,
        type:String
    },
    Country:{
        required:false,
        type:String
    },
    Awards:{
        required:false,
        type:String
    },
    Poster:{
        required:false,
        type:String
    },
    Metascore:{
        required:false,
        type:String
    },
    imdbRating:{
        required:false,
        type:String
    },
    imdbVotes:{
        required:false,
        type:String
    },
    imdbID:{
        required:false,
        type:String
    },
    Type:{
        required:false,
        type:String
    },
    Response:{
        required:false,
        type:String
    },
    Images:{
        required:false,
        type:Array
    },

});
export const schemaDB = {
    actors,
    movieSchema,
    User,
    categorie,
    feedMovie
}